# Generated by Django 2.1.3 on 2018-11-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20181128_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
