# Generated by Django 2.1.3 on 2018-12-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FBUserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('date_joined', models.DateTimeField(verbose_name='Date Joined')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='Mobile')),
                ('fb_id', models.CharField(max_length=200, unique=True, verbose_name='Facebook ID')),
                ('profile_pic', models.CharField(blank=True, max_length=500, verbose_name='Profile Picture')),
                ('gender', models.CharField(blank=True, max_length=10, verbose_name='Gender')),
            ],
        ),
    ]
